{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "artsa.name" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "artsa.name" . }}-api
                port:
                  number: {{ .Values.service.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "artsa.name" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
